### ISSUE TITLE
Accessible content with easy to read text and correct use of semantic elements (must-have)

### ISSUE THREAD

**Issue by Jo-JPEG** [Jo-JPEG/flagstone-project-01#3]
### **User Story 3:**
 As a user with a visual impairment, I want to be able to navigate the site using a screen reader. 
Accessible content with easy to read text and correct use of semantic elements (must-have)

**Acceptance Criteria**

1. The website uses best practices in regard to accessibility 
2. The site can be navigated by screen readers and the text is readable and high-contrast

**Tasks**

- [x] - Ensure all images are correctly described using alt-text
- [x] -Make HTML code as semantic as possible
- [x] -Check code with external resources such as Lighthouse
