### ISSUE TITLE
Additional pages with pictures and content (should-have)

### ISSUE THREAD

**Issue by Jo-JPEG** [Jo-JPEG/flagstone-project-01#5]
### **User Story 5:**
 As a curious individual, I want to read real-life success stories of diversity and inclusion initiatives, so I can see the positive impact these practices can have.

Additional pages with pictures and content (should-have)

**Acceptance Criteria**

1. - The website has additional pages of content linked with the navbar 

**Tasks**

- [ ] - add additional html pages
- [ ] -ensure styling is consistent and all links work correctly
- [ ] -add placeholder content of stories and pictures
